name: ChatPlugin
main: com.ashe.chatplugin.ChatPlugin
version: 1.0
api-version: 1.21
depend: [LuckPerms]
commands:
  chatplugin:
    description: Manage player prefixes and suffixes.
    usage: /chatplugin
